# Generated by Django 2.0.2 on 2018-03-04 01:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happyhour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('well_price', models.CharField(blank=True, max_length=255)),
                ('draft_price', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='business',
            old_name='address',
            new_name='address_1',
        ),
        migrations.AddField(
            model_name='business',
            name='address_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='geolocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='business',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='business',
            unique_together={('name', 'address_1')},
        ),
        migrations.AddField(
            model_name='happyhour',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Business'),
        ),
    ]
